# Generated by Django 3.2.6 on 2021-08-31 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='view',
            new_name='views',
        ),
    ]
