version: '3'

networks:
  web:
    external: true
  internal:
    external: false

services:
  tests:
    build: .
    container_name: tests
    env_file:
      - .env
    command: bash -c 'python3 manage.py test'
    volumes:
      - .:/home/user/web
    restart: always
    networks:
      - web
      - internal
