name: CI

on:
  push:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: set env
        uses: alfir777/django_jatu_ru@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export SECRET_KEY=${{ secrets.SECRET_KEY }}
            export DEBUG=${{ secrets.DEBUG }}
            echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> django_jatu_ru/.env
            echo DEBUG=${{ secrets.DEBUG }} >> django_jatu_ru/.env
      - name: Run tests
        run: docker-compose up --exit-code-from tests tests
