name: CI

on:
  push:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set env
        uses: alfir777/django_jatu_ru@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export SECRET_KEY=${{ secrets.SECRET_KEY }}
            export DEBUG=${{ secrets.DEBUG }}
            mkdir -p /home/runner/work/django_jatu_ru/django_jatu_ru/
            cd /home/runner/work/django_jatu_ru/django_jatu_ru/
            echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
            echo DEBUG=${{ secrets.DEBUG }} >> .env
      - name: Run tests
        run: docker-compose up --exit-code-from tests tests
