name: CI

on:
  push:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: set env
        uses: appleboy/ssh-action@master
        with:
          script: |
            export SECRET_KEY=${{ secrets.SECRET_KEY }}
            export DEBUG=${{ secrets.DEBUG }}
            echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
            echo DEBUG=${{ secrets.DEBUG }} >> .env
      - uses: actions/checkout@v2
      - name: Run tests
        run: docker-compose up --exit-code-from tests tests
